Vin205/Enyanjyoti

src/App.js, src/Educ.js, src/Footer.js, src/Hom.js, src/Nabar.css, src/Nabar.js, src/footer.css
I ADD footer section to all the pages in the website and the footer section is fully responsive and add
transition effect to the social links.
https://github.com/user-attachments/assets/b079331a-0e89-4ba5-9116-4e8e05b56fc0
=> ADD FOOTER SECTION TO THE PAGE #14

package-lock.json, package.json, src/App.js, src/Login.js, src/Nabar.js, src/Signup.js
=> added login signup pages

README.md
Fixes #6
Hey I have updated the readme.md
=> Update README.md Fixes #6

src/App.js
**Changes made:**
Removed repeated code in `App.js`
Solved issue #29
=> Fix: HomePage section repitition is fixed

src/App.js
Implemented a responsive navigation bar that displays a hamburger menu on smaller screens.
The navigation menu is hidden on mobile until the hamburger icon is clicked, at which point it toggles the menu.
https://github.com/user-attachments/assets/693d622e-1fa4-4411-88b6-1d43f9ad38cf
Please assign this issue to me as I would like to work on fixing it. also add the label GSSoC 2024 Extd relaevant and lvl according to the work.
issue number 13
=> FIX THE NAVBAR add Hamburger #13

CODE_OF_CONDUCT.md
fixes #16
Description
This PR introduces a Code of Conduct document for the Enyanjyoti platform to ensure a positive, inclusive, and harassment-free environment for all participants, contributors, and learners. The Code of Conduct outlines expected behaviors, unacceptable actions, and enforcement responsibilities to promote a respectful and collaborative community, particularly focused on education in rural areas.
=> Fix #16 : added CODE_OF_CONDUCT.MD file

README.md
This is with reference to issue #18 . I have the changes as proposed in my issue. 
Please review them and kindly let me know if any changes are required.
=> Add Basic Snapshotting(git status, git commit) , branching and merging commands

src/About.css, src/About.js, src/App.js
I added an About Us page with routing, and also added a gallery slider using React Slick for issue #33 . Here are some screenshots:
Please assign me the the tags before merging and let me know of any issues @skmirajulislam !
=> Added About page with routing and a gallery slider for issue #33

package-lock.json, package.json, src/Footer.js, src/footer.css
#43 Enhanced the UI of the Footer by making it more attractive and user engaging
https://github.com/user-attachments/assets/426c2eef-739c-466a-b94c-77a9e85896d0
@Vin205 @skmirajulislam Kindly review.
=> Enhanced the UI of the footer 

README.md
I have added all the contributors in readme.md file to give them appreciation.
Completed #53
=> Additon of All Contributors | Issue #53

src/components/Signup/Signup.js
Fixes [https://github.com/Vin205/Enyanjyoti/security/code-scanning/4](https://github.com/Vin205/Enyanjyoti/security/code-scanning/4)
To fix the problem, we need to ensure that sensitive information, such as passwords, is not logged in clear text. The best way to address this is to remove the sensitive data from the log statement or to mask it before logging.
- **General Fix:** Avoid logging sensitive information like passwords. If logging is necessary for debugging, ensure that sensitive data is masked or redacted.
- **Detailed Fix:** In the `handleSignup` function, modify the `console.log` statement to exclude the `password` field or replace it with a masked version.
- **Specific Changes:** Update the `console.log` statement on line 28 to log only non-sensitive information or to mask the …
=> Fix code scanning alert no. 4: Clear-text logging of sensitive information

src/components/Login/Login.js
Fixes [https://github.com/Vin205/Enyanjyoti/security/code-scanning/3](https://github.com/Vin205/Enyanjyoti/security/code-scanning/3)
To fix the problem, we need to remove the logging of sensitive information, specifically the password. Instead of logging the entire object containing both the username and password, we can log only the username or a generic message indicating that a login attempt is being made. This way, we avoid exposing sensitive information in the logs.
- Remove the logging of the password on line 22.
- Replace it with a safer logging statement that does not include sensitive information.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._
=> Fix code scanning alert no. 3: Clear-text logging of sensitive information

frontend/package-lock.json, frontend/public/index.html, frontend/src/pages/About/About.css, frontend/src/pages/About/About.js, frontend/src/pages/Home/Hom.css, frontend/src/pages/Home/Hom.js
Added a scroll to top button. please review the or and merged accordingly under gssoc-extended and hacktober fest accepted levels
https://github.com/user-attachments/assets/604c9f02-7f3c-44b9-9b94-9f5b3eb5fc3b
=> solved issue #47

README.md, frontend/package-lock.json, frontend/package.json, frontend/src/pages/About/About.css, frontend/src/pages/About/About.js, frontend/src/pages/Home/Faqs.css, frontend/src/pages/Home/Hom.css
**1) ADDED IMAGE CAROUSEL AND FIXED BG UI ISSUE IN ABOUT SECTION**
https://github.com/user-attachments/assets/e1bba825-9162-4692-a321-8f9116816731
**2) FIXED IMAGE HEIGHT IN HOME PAGE**
**3) IMPROVED MARGINS IN FAQ PAGE**
=> Added image carousel in about section 

frontend/src/App.js, frontend/src/components/Login/Login.js, frontend/src/components/Signup/Signup.js
Made the login and Signup page . previously it was looking as following :- 
i redesigned it and align it  properly . @skmirajulislam  Please review the pr and merge it under gssoc-extended and hactober fest approved and with a suitable level. Following are the login and signup up that i designed :-
=> solved issue #49

frontend/src/components/Login/Login.js, frontend/src/components/Navbar/Navbar.js, frontend/src/components/Signup/Signup.js
I have tried my best to maintain the coding standards while fixing the issue
=> FIxed Navbar vertical alignment and Login/Signup Components

frontend/src/App.js, frontend/src/components/Navbar/Navbar.js
Make navbar look good . Remove the duplications of options . @skmirajulislam  please review the pr and merge accordingly.
=> solved issue #86

frontend/src/components/Login/Login.js, frontend/src/components/Signup/Signup.js
Added Visibility off / on button on login and sign-up pages . @skmirajulislam  please look after the PR and merge it accordingly
=> solved issue #88

frontend/package-lock.json, frontend/package.json, frontend/src/components/Navbar/Navbar.css, frontend/src/components/Navbar/Navbar.js
Changed header component which looks attractive and beautiful
=> New Header Component

README.md
Updated the Contributors profile in the Readme.md file
=> Updated Contributors Profile

frontend/package-lock.json, frontend/package.json, frontend/src/App.js, frontend/src/components/Firebase/firebase.js, frontend/src/components/Firebase/logout.js, frontend/src/components/Firebase/useAuth.js, frontend/src/components/Login/Login.js, frontend/src/components/Signup/Signup.js, frontend/src/pages/Dashboard/Dashboard.js
This pull request is related to #89  and introduces the following features:
- **Login**: Users can log in using their email and password.
- **Signup**: New users can create accounts with email and password authentication.
- **Logout**: Users can log out from their sessions seamlessly.
- **Dashboard Route**: A placeholder dashboard route has been created, which currently serves as a dummy page.
For the time being, the username field has been removed, and authentication is limited to email and password. I plan to reintroduce the username feature once this PR is merged.
- Please ensure that email/password authentication is enabled in the Firebase console for this feature to function correctly.
- Further enhancements, including the reintroduction of the username feature, will be developed …
=> Implement Login, Signup, and Logout Features with Dashboard Route (Fix #89)

.github/workflows/Greetings.yml
closes #104 
This is a PR raised for the level1 enhacement of the repository where the Github Actions bot that send a message for the new users who raise a new PR or an issue in the project.
Please add level1 and gssoc-ext labels to this PR.
Thank you.
=> #Add Github Greetings Bot

README.md
=> added featured in table

backend/.dockerignore, backend/dockerfile, frontend/.dockerignore, frontend/dockerfile
#110 Added frontend docker and backend docker as well .
=> issue #110 Dockerize the Application

frontend/src/components/Footer/Footer.js
Fixes #135 Edit the twitter icon correctly, in social icons website uses the previous icon of twitter now it will use correctly '**X**' icon.
@skmirajulislam Please review my PR and merge accordingly.
=> Bug/Twitter Icon

frontend/src/components/Login/Login.js, frontend/src/components/Signup/Signup.js
Fixed the  UI  of showing the password icon
=> Fixed the ui of misplacement of showpassword icon

frontend/src/components/Login/Login.js, frontend/src/components/Signup/Signup.js
i fixed the responsiveness issue caused by the Eye icons in login and signup page 
Sign up page:
Login Page:
**please Add gssoc-ext and level1 label before merge** @Vin205
=> Fixed Responsiveness of login and signup pages issue #109

frontend/src/pages/About/About.css, frontend/src/pages/About/About.js
https://github.com/user-attachments/assets/a07ede84-a469-4106-8235-d23b233d1792
=> Changed the CSS of the about page and the swiper slide #107

frontend/src/App.js, frontend/src/pages/Error/index.js
Fixes #133 When we enter a wrong path then browses show its default 404 page but now it will show my error path of invalid path.
**TEST VIDEO:**
https://github.com/user-attachments/assets/e020bd60-3658-4388-8054-2c831b3edf28
=> BUG: Invalid or wrong path route added

frontend/src/components/Navbar/Navbar.js, frontend/src/pages/Home/Hom.css, frontend/src/pages/Home/Hom.js
Fixes #126  When we click on site icon then it will open in new tab by onClick event handler.
@skmirajulislam Please review my PR and merge accordingly with the labels.
=> Bug: Site Icon open in tab

frontend/src/pages/Home/Hom.css, frontend/src/pages/Home/Hom.js
Fixes #121  When we see the cards in home page it looks very simple but now it will look something better when we hover it it scale(1.1) and also drop a small shadow on hover Effect.
@skmirajulislam Please review my PR and merge accordingly!
=> Design: Home page cards

frontend/src/components/Navbar/Navbar.js
now user can see all 4 options from the toggle button.
=> add loan option in toggle button

frontend/src/pages/Loan/Loan.css, frontend/src/pages/Loan/Loan.js
#161: 
-Improve loan calculator form with a new Payment Frequency option (monthly, bi-weekly, weekly).
-Display Monthly Payment, Total Payment, and Total Interest after calculation.
can i work on this ??
PREVIOUS: 
NEW:
=> Improve Loan Calculator & Loan Summary Display 

frontend/src/components/Footer/footer.css, frontend/src/components/Navbar/Navbar.css, frontend/src/pages/About/About.css, frontend/src/pages/Contact/Contact.css, package-lock.json
This PR solves the issue #163  ,changes made to footer buttons,about us and contact us page
=> minor changes

frontend/src/pages/Home/Hom.css, frontend/src/pages/Home/Hom.js
hey @Vin205 , 
i just solved the issue mentioned above and created this PR. This PR helps improve the UI/UX  for the HomePage and makes it more visually appealing and dynamic with animations.
The previous code has so much complexity that it was complex to find the CSS properties which were inherited to this home page , took hours to find it then solved it. So i think this PR needs level 2 label (if you think the same).
apart from that 
1) resized login & signup buttons
2) fixed font size for title and subtitle 
3) fixed padding so that the various sections look distinguished
here's a preview :
=> Enhancement : Improved UI 

frontend/src/components/Signup/Signup.js
#182 
Issue resolved
hello PA,
I have added the strong password function in the signup page.
=> Strong password

frontend/src/components/Navbar/Navbar.css, frontend/src/components/Navbar/Navbar.js, frontend/src/pages/Home/Hom.css
Hey!
As discussed in the issue #184, I have successfully made some enhancements in the navbar,
- I made some changes in the colour scheme of the navbar, to make a a bit more appealing (from white to #191B1C
- Secondly, I made some changes to the logo present on the navbar to give it a better look overall.
=> Enhancements in design of the navbar

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, frontend/src/components/Login/Login.js, frontend/src/components/Signup/Signup.js, frontend/src/validations/validation.js, package-lock.json, package.json
Hello
I have added proper input validations for login and signup pages with error message display
Pls check it
=> add input validations

frontend/src/components/Login/Login.js
Hi @Vin205 !! As specified in issue #203 I have made the necessary changes to login.js. Please note the following changes made:-
Refactoring the Login component by introducing three new components: LoginHeader, LoginForm, and LoginFooter, each encapsulating parts of the original Login component's functionality. This allows decentralization and increased organization of the code. 
Please receive this request and merge this file to the main. 
Thanks,
Yash Vashishth
(Contributor, GSSoC'24 and Hacktoberfest)
=> [feat], [perf] : Changed features of login.js for ease of access

frontend/src/components/Footer/footer.css, frontend/src/components/Navbar/Navbar.css
This PR aligns the design and functionality of the footer and navbar to create a more cohesive and consistent user interface. By [mention specific changes, e.g., matching colors, fonts, or spacing], this update improves the overall visual appeal and usability of the website. The new design also ensures a seamless transition between the footer and navbar, enhancing the user experience and reducing confusion..                                                                                                                                                                                               It resolves issue #199 
. Please try to merge it , It has no conflicts
=>  Revamped Footer and Navbar for Enhanced User Experience

.gitignore, .husky/pre-commit, backend/.husky/pre-commit, backend/.prettierrc, backend/READEME.md, backend/eslint.config.js, backend/package-lock.json, backend/package.json, backend/server.js, backend/src/constants/index.js, backend/src/controllers/auth/loginUser.js, backend/src/controllers/auth/registerUser.js, backend/src/controllers/index.js, backend/src/models/User.js, backend/src/routes/authRoutes.js, backend/src/utils/db/connectDB.js, backend/src/utils/index.js, eslint.config.js, package-lock.json, package.json
#188 
This PR adds some useful tooling for the backend to ensure consistent code quality and formatting before pushing code. Here's what's included:
- **Husky Pre-Commit Hook**: Now, every time you try to commit code in the backend, Husky will automatically run ESLint and Prettier to check for linting issues and formatting problems.
- **ESLint Configuration**: ESLint is set up specifically for the backend with appropriate rules to catch common mistakes and ensure consistency.
- **Prettier Configuration**: Prettier is configured to auto-format the code based on defined styling rules.
This setup helps ensure that all code going into the repo is clean and follows consistent standards. Let me know if you have any feedback or suggestions!
=> Set Up Husky Pre-Commit Hook and ESLint/Prettier for Backend

frontend/src/components/Footer/footer.css, frontend/src/pages/Home/Hom.css
The website was not mobile-responsive. So, I am making this pull request which includes updated code and the website is now mobile-responsive.
This PR fixes issue: #204 
Please review and merge the PR if no conflicts are there. 
Let me know in case of any conflicts while merging the pull request.
=> [Fix]: makes website mobile-responsive

.github/workflows/autolabeler.yml, .github/workflows/restrict_issues.yml
=> Add GitHub Workflow for Auto-Closing Similar Issue Requests and autolabeler

frontend/public/index.html, frontend/src/App.js, frontend/src/components/Navbar/Navbar.js, frontend/src/pages/Contributor/ContributorsPage.jsx
Added the cobtributors page and used tailwind css.
closes #193 
ScreenShorts : 
@Vin205 @skmirajulislam Please review this PR and merge it and assign this to me and put relevent labels like gssoc 2024 ext, hacktoberfest and level.
i think it can be level 3 because the page is very important in open source to showcase the efforts of the people contributing in building it and it is not static it is dynamic as a new contributor is added to your repo it will be automatically added there so this is the beauty of this.
=> Added the cobtributors page.

frontend/src/components/Footer/Footer.js, frontend/src/components/Footer/footer.css
This pull request focuses on enhancing the "Contact Us" form in the footer, along with overall UI improvements. The key updates include:
*Contact Form Styling: Redesigned the "Contact Us" form for better usability, including improved input fields and a more visually appealing button.
*UI Enhancements: Updated the footer's color scheme and layout for a cleaner and more modern look, ensuring a better user experience and also the maintaining the buttons transition effects.
@Vin205 Please review this PR....
Issue number - `Fix #190`
=> Add Contact Us Form, enhance the Footer and also Responsive

frontend/package-lock.json, frontend/src/pages/Home/Hom.css
Sized the Buttons of login and signup to more adjustable according to the website
=> Updated the Buttons

frontend/src/pages/Loan/Loan.css
**Color Variables:** The code uses CSS variables for consistent theming across the page. This makes future adjustments easy, as changing a variable will update the style throughout the file.
**Hover and Animation Effects:** Various elements, such as buttons and sections, have hover effects that change their appearance and animations to make the interface feel more dynamic. These include scaling effects, color transitions, and keyframe animations.
**Responsive Design:** The code includes media queries to ensure that the layout adjusts well on tablets and mobile devices, maintaining the responsiveness from the original design.
**Modern Design Enhancements**: The CSS has added subtle touches like gradient backgrounds for the title, animations for the fade-in effect, and accent lines under …
=> UI: Improve the UI of loan page

frontend/src/components/Login/Login.js, frontend/src/components/Signup/Signup.js
Fixes #233  Added footer in login and sign up page.
@skmirajulislam Please review it and merge accordingly!
=> BUG: Footer added in login and signup form

frontend/src/components/Login/Login.js, frontend/src/components/Signup/Signup.js
When user try to login then loading will start if it successfully logged in then a msg will show of successfully login and when user try to create account then loading start if it is not able to create then msg will be shown Signup failed or if it successfully able to create account then it show successfully account create.
@skmirajulislam Please review it and merge accordingly with the labels.
=> BUG: Notification added in login and signup

backend/package-lock.json, frontend/src/components/Navbar/Navbar.css, frontend/src/pages/Home/Hom.css, package-lock.json
Fixes #270 : Improved the Navbar
Problem was in UI , irrelevant paths were also visible which was looking ugly + made sure to keep it responsive
https://github.com/user-attachments/assets/cef612fe-a6b0-4f1e-9c89-8379392010e8
=> [Fix]  Issue #270 resolved : Improved the Navbar problems

frontend/src/pages/Home/Hom.css
scroll bar added : Scroll bar added #232 done
if you dont like the color of scroll bar you can change in Hom.css file or you just tell me which color you want for scroll on your website.
https://github.com/user-attachments/assets/83d4fb61-8dee-40d5-add3-8d89ac66dd2c
=> scroll bar added : Scroll bar added #232 done

frontend/src/components/Footer/Footer.js, frontend/src/components/Footer/footer.css
=> Revamped the footer, enhace the look and feel of the footer 

frontend/src/pages/career/career.css, frontend/src/pages/career/career.js
=> Add career page 

frontend/package-lock.json, frontend/public/index.html, frontend/src/pages/Contact/Contact.css, frontend/src/pages/Contact/Contact.js
Improved UI of Contact page .
previously it was looking as :- 
Now it is looking as :- 
@skmirajulislam  please merge the PR accordingly.
=> solved issue #262

frontend/src/pages/Contact/Contact.js
Fixes #276 Improving the allignment of ContactUs page now it will not hide by the navbar of the website:)
@skmirajulislam Please review it and merge accordingly!
=> BUG: Improving the Allignment of ContactUs page

frontend/src/components/Navbar/Navbar.css, frontend/src/components/Navbar/Navbar.js
This PR was aimed to fix #239 for UI enhancement similar to the Footer
https://github.com/user-attachments/assets/e3ef4b67-330b-426c-91b1-ef16c3861f15
https://github.com/user-attachments/assets/4dcddbac-77c7-4be1-beb8-7fbb2e6c0bf4
- Updated color scheme for better contrast and readability, ensuring adherence to accessibility standards.
- Enhanced hover effects on navigation links and buttons for clearer feedback on interaction.
- Refined padding and spacing to create a more balanced and visually appealing layout.
@skmirajulislam  Please let me know if you see any areas that may need further improvement.
=> Fix: Navbar- Active Link and Formatting Issues

frontend/src/components/Footer/footer.css, frontend/src/pages/Home/Faqs.css, frontend/src/pages/Home/Hom.css
Aligned the part assigned and added space to them.Now even if you hover over them they are not overlapping each other
https://github.com/user-attachments/assets/016d28c1-edf2-43fc-be49-83c6552e5612
and my issue number is #289
=> Alignment of certain part of the website 

frontend/src/components/Signup/Signup.js
**Issue_id**: #312 
**Overview:** This PR introduces real-time email validation in the Signup component to ensure users provide email addresses from trusted email providers. The validation checks the email format and verifies that the domain belongs to a list of predefined trusted providers: Gmail, Yahoo, Outlook, iCloud, and Hotmail.
**Changes Made:**
- Added a state variable emailError to manage error messages related to email validation.
- Implemented regex checks to validate email format.
- Checked the email domain against a list of trusted providers.
- Displayed error messages in real time as the user types their email.
**Benefits:**
- Improves user experience by providing immediate feedback on email validity.
- Ensures that only trusted email providers are used for account creation, …
=> Implement Real-Time Email Validation for Trusted Domains in Signup Component

.github/ISSUE_TEMPLATE/bug_report_template.md, .github/ISSUE_TEMPLATE/custom_issue_template.md, .github/ISSUE_TEMPLATE/feature_request_template.md
Fixes #306  Adding issues templates in website now user can have 3 option for creating any issue, BUG, Custom_issue, Feat.
@skmirajulislam Please review and merge it.
=> Feat: Adding Issues Templates

frontend/src/App.js, frontend/src/pages/Preloader/Preloader.css, frontend/src/pages/Preloader/Preloader.jsx
Solved :
Issue no #343 
https://github.com/user-attachments/assets/6de694d8-4696-4afc-a617-58b5ea585809
=> Added Animeted Pre Loader : Issue no #343

frontend/src/pages/Loan/Loan.css, frontend/src/pages/Loan/Loan.js
Loan calculator UI and payment frequency issue #339  
This pull request addresses the inconsistencies in the loan calculator's user interface and resolves the issue with payment frequency calculations. The updated design improves the layout, standardizes the styling of buttons and input fields, and ensures a more consistent and polished user experience. Additionally, the functionality for recalculating loan payments based on different payment frequencies (monthly, bi-weekly, and weekly) has been corrected, allowing for accurate and dynamic value updates when the frequency is changed.  
[Bug Fix]: Fixed UI inconsistencies and payment frequency recalculation for the loan calculator  
https://github.com/user-attachments/assets/02b80d21-95a8-413e-beb0-b978f64eab10
The changes ensure that the …
=> Fixed UI inconsistencies and payment frequency recalculation for the loan calculator

frontend/src/pages/Home/Faqs.jsx
Issue no #341
I have changed "Frequently Asked Questions" to "FAQs" 
- Read all the codebase and found faqs.js
- Made changes to it.
It's done. Please feel free to check. Thanks for assigning this issue.
=> "Frequently Asked Questions" to "FAQs" #341

frontend/src/pages/Contact/Contact.css
This pull request introduces smooth hover effects to the input fields and the submit button in the contact form. When hovered over, the input fields slightly grow in size, providing a more engaging user experience. Additionally, the submit button also enlarges on hover for better visibility and interactivity.
- Added CSS transitions to input fields and the submit button.
- Implemented scale transformation on hover for input fields and the button.
- Enhanced padding for better appearance and usability.
fixes: #362
=> Add Smooth Hover Effects to Contact Form

frontend/src/pages/Home/Hom.css
There was some error in Git, that's why I am generating a PR in this way. For reference I am solving "Enhancement: Add hover effect to the main heading for a more dynamic appearance #310" (https://github.com/Vin205/Enyanjyoti/issues/310). I was assigned to work on it and here is my contribution.
Before 
After
=> Enhancement: Add hover effect to the main heading for a more dynamic appearance #310

frontend/src/pages/Contact/Contact.js
solved #280 
working demo:
https://github.com/user-attachments/assets/b15e9c61-d816-4a17-87ec-d09c52ec3d09
=> Improved Message Display and Validate Character Length on "Contact Us" Page

frontend/src/components/Signup/Signup.js
#281 
- Added a gradient background to the signup card:
The card now has a subtle gradient from light gray to slightly darker gray, creating a soft, modern look.
- Implemented a glow effect:
A blue glow (box-shadow) was added around the card, giving it a subtle highlight.
- Created a hover animation:
When users hover over the card, it slightly lifts up and the glow intensifies, providing visual feedback.
- Increased padding inside the card:
The internal padding of the card was increased to 2rem, giving the content more breathing room.
- Applied smooth transitions:
A transition effect was added to make the hover animation smoother and more pleasing to the eye.
=> Updated Signup.js

frontend/src/components/Footer/footer.css, frontend/src/components/Login/Login.js
[BUG]: Inconsistent Alignment of Login and Footer Containers #369 
This pull request addresses the issue of inconsistent alignment between the Login and footer containers. The changes implement vertical alignment for both containers, enhancing the visual flow and overall user experience on the page.
Aligning the Login and footer containers vertically creates a more user-friendly layout and improves the visual hierarchy on the page, leading to a better overall user experience.
=> Fixed Inconsistent Alignment of Login and Footer Container

Enyanjyoti/Enyanjyoti.html, Enyanjyoti/button.html
⭐Created a donation page 
➡️ For the welfare of everyone , espacially the future generation
➡️Changes created 
👉🏻The Donation Page
👉🏻The Button
=> Created A Donation page

frontend/src/pages/Contact/Contact.css
[BUG]: Contact Us Form Submit Button UI Breaking in Mobile View #373
This pull request addresses the issue of the submit button in the "Contact Us" form, where the button's content extends outside its boundaries in mobile view. The changes include updates to the button's styling to ensure proper containment of the text, maintaining a consistent appearance across various screen sizes.
The updated styling ensures that the submit button maintains a professional appearance across different screen sizes, including mobile view. This fix helps improve the user experience when submitting inquiries via the Contact Us form.
=> Fixed Contact Us Form Submit Button UI Breaking in Mobile View

frontend/src/components/Signup/Signup.js
[BUG]: Inconsistent Alignment of SignUp and Footer Container #371
This pull request addresses the issue of inconsistent alignment between the SignUp and footer containers. The changes implement vertical alignment for both containers, enhancing the visual flow and overall user experience on the page.
Aligning the SignUp and footer containers vertically creates a more user-friendly layout and improves the visual hierarchy on the page, leading to a better overall user experience.
=> Fixed Inconsistent Alignment of SignUp and Footer Container

frontend/src/components/Navbar/Navbar.js, frontend/src/pages/Map/map.html
Made this map and added the table 
https://github.com/user-attachments/assets/2fa9866b-2dfd-42e1-842d-7cc4b1314fbe
=> solved #473   Added literate and illetate states on india map, table

frontend/src/components/Navbar/Navbar.css
Hi @Vin205
I recently updated the navbar menu for your project to make it more attractive and user-friendly. Enhance readability, improve navigation, and give your site a visually appealing touch that stands out with these simple yet impactful design updates. I've attached screenshots of the changes that contribute to this enhancement to improve the overall design.
I'm looking forward to hearing feedback from you!
Best regards,
@khurshed07
https://github.com/khurshed07
=> Modify_Navbar

README.md
Related Issue: #453 
This pull request improves the visual appeal of the project by:
1. Adding a visually appealing GIF to the project title in the `README.md` file.
2. Centering the project title and GIF to enhance its prominence and create a more engaging introduction for users viewing the repository.
The changes aim to:
- Enhance user experience by making the project title more dynamic and attractive.
- Provide a clear and welcoming display at the top of the repository for new contributors and viewers.
Please label this PR with:
- gssoc-ext for contributions under GirlScript Summer of Code Extended.
- hacktoberfest-accepted to ensure it counts towards Hacktoberfest.
https://github.com/user-attachments/assets/24c1e63a-3431-4daa-90cc-5f7c1d596476
=> Update README to Enhance Project Title with GIF for Improved Aesthetics (#453)

frontend/public/index.html
#326 
https://github.com/user-attachments/assets/388909b3-b353-4e14-9040-63354ca6283d
=> add chatbot integration to website 

frontend/src/components/Signup/Signup.js
- **Hover Effects**: Added smooth hover effects to the signup card, buttons, and input fields for improved user interaction and visual feedback.
- **Styling Updates**: Updated CSS to enhance the overall appearance and interactivity of the signup component.
- The signup card now features a subtle shadow and transform effect on hover, creating a more engaging experience for users.
- Buttons have a smoother color transition and slight upward movement on hover, enhancing usability.
- Input fields have been styled to highlight focus, providing a clearer indication of user actions.
These changes aim to improve the user experience by making the signup process visually appealing and interactive, which can lead to higher user engagement and satisfaction.
fixes: #476 
- Please merge it.
- fixes: …
=> Enhanced Signup Component

frontend/src/pages/Loan/Loan.css
This pull request updates the CSS styles for the loan calculator buttons to achieve center alignment. The changes include:
- Adjusted the button container to use flexbox for vertical alignment.
- Centered the button text and ensured consistent spacing between form elements.
These updates enhance the user interface by providing a more balanced and visually appealing layout for the loan calculator.
- Updated `.calculator-form` styles to use `align-items: center`.
- Added flexbox properties to `.loan-button` for text alignment.
Please review the changes and let me know if any adjustments are needed!
fixes: #458
=> Center Align Buttons in Loan Calculator
